name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet le déclenchement manuel
    inputs:
      branch:
        description: 'Branch to build and push'
        required: true
        default: 'main'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_ID }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Build and push Angular app Docker image
        working-directory: ./conversion-devises-frontend
        run: |
          docker build -t cicdberard/cicdberard/front .
          docker push cicdberard/cicdberard/front

      - name: Build and push API JavaScript Docker image
        working-directory: ./
        run: |
          docker build -t cicdberard/cicdberard/api .
          docker push cicdberard/cicdberard/api
